# Generated by Django 6.0 on 2025-12-05 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('fio', models.TextField(blank=True, null=True, verbose_name='ФИО')),
                ('user_type', models.CharField(choices=[('client', 'Клиент'), ('employee', 'Сотрудник')], max_length=10, verbose_name='Тип пользователя')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Название компании')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
