# Generated by Django 6.0 on 2025-12-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(null=True, upload_to='business', verbose_name='Изображение'),
        ),
    ]
