# Generated by Django 6.0 on 2025-12-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_userprofile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_create_projects', 'Может создавать проекты')], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
