# Generated by Django 6.0 on 2025-12-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_create_projects', 'Может создавать проекты'), ('can_see_EmployeesView', 'Может видеть страницу добавления сотрудников')], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
