# Generated by Django 6.0 on 2025-12-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_see_ClientsView', 'Может видеть страницу добавления клиентов'), ('can_see_FavoursView', 'Может видеть страницу добавления услуги'), ('can_create_projects_admin', 'Может создавать проекты с вкладкой выбора клиента'), ('can_create_projects', 'Может создавать проекты без вкладки выбора клиента'), ('can_add_project_services', 'Может добавлять услуги в проект'), ('can_see_ProjectServicesView', 'Может видеть страницу добавления услуги в проект'), ('can_see_EmployeesView', 'Может видеть страницу добавления сотрудников')], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
