# Generated by Django 6.0 on 2025-12-05 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_project_review_alter_favour_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.project'),
        ),
    ]
