# Generated by Django 6.0 on 2025-12-05 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_review_pr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.TextField(verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('employee_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('favour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.favour', verbose_name='Услуга')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Услуга в проекте',
                'verbose_name_plural': 'Услуги в проектах',
            },
        ),
    ]
