# Generated by Django 6.0 on 2025-12-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_project_client_user_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='picture',
            field=models.ImageField(null=True, upload_to='business', verbose_name='Изображение'),
        ),
    ]
